(withs (e1 '(a b c)
        e2 (cons 'd e1)
        e3 (cons 'f (cons 'e e1)))
  (test (is (common-tail e2 e3) e1) t)
  (test (is (common-tail e1 e2) e1) t)
  (test (is (common-tail e2 e1) e1) t)
  (test (is (common-tail e1 e3) e1) t)
  (test (is (common-tail e3 e1) e1) t)
  (test (common-tail '(a) '(b)) nil))
